### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by EmilMoe** [mojopollo/laravel-json-schema#6]
You should have the options as a subset array instead of merging different values into a string.

For simple things:
'name' => 'string'

For more advanced
'name' => [
type: 'string',
length: 255
]

**Comment by mojopollo** [comment]
I do like that, at first I was torn between making field definitions in array format or keeping things like they are in Jeffery Way's extended generators as I was already used to defining schema that way.

How would you propose single attributes like "unique" be defined? I thought of doing this as a boolean:

```json
"name": {
  "unique": true
}
```

or


which would mean you could also write

```json
"name": {
  "unique": false
}
```

which the parser could just ignore I guess. I would like to have a cleaner definition that just a long string, I would just a
